/// --create-config: the `.editorconfig` block that changes nothing — every
/// rule at the default this build applies anyway, every run-level key at
/// its own default, a comment on each saying what turning it round does.
/// Appended to the directory's `.editorconfig` (written when there is
/// none); a key already present is never rewritten.
module CSharp.Refactor.Tool.ConfigFile

open System
open System.IO
open System.Text
open System.Text.RegularExpressions
open CSharp.Refactor

[<Literal>]
let Marker = "# ---- csharp-refactor ----"

let private rulesAsRows () =
    RuleCatalog.rules
    |> List.map (fun r -> r.Code, RuleCatalog.name r.Category, r.Default)

/// The block, headed by a `[*.cs]` section so it stands on its own.
let defaultConfigText () =
    let text = StringBuilder()
    let line (s: string) = text.AppendLine s |> ignore

    line Marker
    line "# Generated by `csharp-refactor --create-config`: every value below is this"
    line "# version's default, so an untouched block changes nothing. Delete a line to"
    line "# follow the tool's default for it as that default changes between versions;"
    line "# keep a line to pin today's answer."
    line "[*.cs]"
    line ""
    line "# Does anything OUTSIDE this assembly link against its public declarations?"
    line "# false says this is a leaf (an application, an internal tool): the rules that"
    line "# change a declaration's compiled shape then treat public as internal. With"
    line "# no setting the compilation answers: an Exe is a leaf, a library is not."
    line "# csharp_refactor.public_api = false"
    line ""
    line "# --api-changes on every run: fixes that rewrite call sites across the"
    line "# solution. Implies public_api = false."
    line "csharp_refactor.api_changes = false"
    line ""
    line "# What a #pragma warning disable / [SuppressMessage] is worth:"
    line "#   all             it silences the finding (what editors do regardless)"
    line "#   no-correctness  correctness findings are reported anyway, never fixed"
    line "#   none            every suppressed finding is reported anyway"
    line "csharp_refactor.suppressions = all"
    line ""
    line "# Extra paths never analysed, ADDITIVE over the built-in defaults (bin, obj,"
    line "# node_modules, generated sources). Semicolon-separated; segment, path or glob."
    line "csharp_refactor.ignore_paths ="
    line ""
    line "# Every rule this build knows, at its default. `none` turns one off;"
    line "# `suggestion` turns a default-off one on."

    let rows = rulesAsRows ()

    for category in RuleCatalog.all do
        let name = RuleCatalog.name category

        let inCategory =
            rows
            |> List.filter (fun (_, c, _) -> c = name)
            |> List.sortBy (fun (code, _, _) -> code)

        if not inCategory.IsEmpty then
            line ""
            line $"# ---- {name} ({inCategory.Length}) ----"

            for code, _, enabledByDefault in inCategory do
                let value =
                    if enabledByDefault then
                        (if RuleCatalog.isPriority code then
                             "warning"
                         else
                             "suggestion")
                    else
                        "none"

                let summary = (RuleCatalog.describe code).Replace('\n', ' ').Replace('\r', ' ')
                line $"dotnet_diagnostic.{code}.severity = {value}  # {summary}"

    text.ToString()

/// Write or append the block. Keys the existing file already sets are
/// left as they are and their lines dropped from the block.
let writeInto (directory: string) : Result<string, string> =
    let path = Path.Combine(directory, ".editorconfig")

    try
        let existing = if File.Exists path then File.ReadAllText path else ""

        if existing.Contains Marker then
            Error $"{path} already carries a csharp-refactor block — edit it, or delete the block to regenerate it."
        else
            let keyOf (l: string) =
                let m = Regex.Match(l, @"^\s*([A-Za-z0-9_.]+)\s*=")

                if m.Success then
                    Some(m.Groups.[1].Value.ToLowerInvariant())
                else
                    None

            let present = existing.Split('\n') |> Array.choose keyOf |> Set.ofArray

            let block =
                (defaultConfigText ()).Split('\n')
                |> Array.filter (fun l ->
                    match keyOf l with
                    | Some k -> not (present.Contains k)
                    | None -> true)
                |> String.concat "\n"

            let content =
                if existing = "" then "root = true\n\n" + block
                elif existing.EndsWith "\n" then existing + "\n" + block
                else existing + "\n\n" + block

            File.WriteAllText(path, content)
            Ok path
    with
    | :? IOException
    | :? UnauthorizedAccessException as e -> Error $"Could not write {path}: {e.Message}"
