/// --create-config: the `.editorconfig` block that changes nothing — every
/// rule at the default this build applies anyway, every rule's knob at its
/// own default (RuleCatalog.knobs), every run-level key at its own default, a comment on each saying what turning it round does.
/// Appended to the directory's `.editorconfig` (written when there is
/// none); a key already present is never rewritten.
module CSharp.Refactor.Tool.ConfigFile

open System
open System.IO
open System.Text
open System.Text.RegularExpressions
open CSharp.Refactor

[<Literal>]
let Marker = "# ---- csharp-refactor ----"

let private rulesAsRows () =
    RuleCatalog.rules
    |> List.map (fun r -> r.Code, RuleCatalog.name r.Category, r.Default)

/// The block, headed by a `[*.cs]` section so it stands on its own.
let defaultConfigText () =
    let text = StringBuilder()
    let line (s: string) = text.AppendLine s |> ignore

    line Marker
    line "# Generated by `csharp-refactor --create-config`: every value below is this"
    line "# version's default, so an untouched block changes nothing. Delete a line to"
    line "# follow the tool's default for it as that default changes between versions;"
    line "# keep a line to pin today's answer."
    line "[*.cs]"
    line ""
    line "# Does anything OUTSIDE this assembly link against its public declarations?"
    line "# false says this is a leaf (an application, an internal tool): the rules that"
    line "# change a declaration's compiled shape then treat public as internal. With"
    line "# no setting the compilation answers: an Exe is a leaf, a library is not."
    line "# csharp_refactor.public_api = false"
    line ""
    line "# --api-changes on every run: fixes that rewrite call sites across the"
    line "# solution. Implies public_api = false."
    line "csharp_refactor.api_changes = false"
    line ""
    line "# What a #pragma warning disable / [SuppressMessage] is worth:"
    line "#   all             it silences the finding (what editors do regardless)"
    line "#   no-correctness  correctness findings are reported anyway, never fixed"
    line "#   none            every suppressed finding is reported anyway"
    line "csharp_refactor.suppressions = all"
    line ""
    line "# Do the Microsoft analyzers and their fixers really run on this code"
    line "# (NetAnalyzers referenced, IDE rules enforced in the build, dotnet format in"
    line "# the loop)? true: a rule whose Microsoft twin is on in this file stands down"
    line "# for its shapes, so nothing is reported twice. false: it reports and fixes"
    line "# them anyway - a severity alone proves no analyzer is loaded."
    line "csharp_refactor.skip_microsoft_duplicates = false"
    line ""
    line "# Extra paths never analysed, ADDITIVE over the built-in defaults (bin, obj,"
    line "# node_modules, generated sources). Semicolon-separated; segment, path or glob."
    line "csharp_refactor.ignore_paths ="
    line ""
    line "# Preprocessor symbols every run defines, like --define: code under"
    line "# #if LOCAL_BUILD is otherwise not analysed at all, and a fix elsewhere can"
    line "# break it unseen. Semicolon-separated; added to each project's own"
    line "# DefineConstants (DEBUG, TRACE stay), never replacing them. Read for the"
    line "# whole run from the .editorconfig nearest the target."
    line "csharp_refactor.defines ="
    line ""
    line "# Every rule this build knows, at its default. `none` turns one off;"
    line "# `suggestion` turns a default-off one on."

    let rows = rulesAsRows ()

    for category in RuleCatalog.all do
        let name = RuleCatalog.name category

        let inCategory =
            rows
            |> List.filter (fun (_, c, _) -> c = name)
            |> List.sortBy (fun (code, _, _) -> code)

        if not inCategory.IsEmpty then
            line ""
            line $"# ---- {name} ({inCategory.Length}) ----"

            for code, _, enabledByDefault in inCategory do
                let value =
                    if enabledByDefault then
                        (if RuleCatalog.isPriority code then
                             "warning"
                         else
                             "suggestion")
                    else
                        "none"

                let summary = (RuleCatalog.describe code).Replace('\n', ' ').Replace('\r', ' ')
                line $"dotnet_diagnostic.{code}.severity = {value}  # {summary}"

                // the rule's tunables at this build's default, so the knob is
                // found in the file rather than only in Rules.md; one whose
                // default is not a single value stays commented out, since any
                // value written would pin one
                for knob in RuleCatalog.knobsOf code do
                    match knob.Default with
                    | Some v -> line $"csharp_refactor.{code}.{knob.Name} = {v}  # {knob.Summary}"
                    | None -> line $"# csharp_refactor.{code}.{knob.Name} =  # {knob.Summary}"

    text.ToString()

/// The run-level keys (`csharp_refactor.<key>`): reserved, so none is ever
/// taken for a rule code or a rule's knob, and `csharp_refactor.defines`
/// in particular never for a rule named DEFINES.
let runLevelKeys =
    set
        [
            "public_api"
            "api_changes"
            "suppressions"
            "skip_microsoft_duplicates"
            "ignore_paths"
            "hints"
            "defines"
        ]

/// The key `--define`'s config twin is read from.
[<Literal>]
let DefinesKey = "csharp_refactor.defines"

/// `csharp_refactor.defines` in one `.editorconfig`'s text: None when the
/// file does not set it, else the symbols and the entries that are no
/// symbol (for the run to name). `;`- or `,`-separated; a trailing
/// `# comment` is not part of the value. Any section counts: the key is
/// run-level, not per file. The last assignment in the file wins, as an
/// ini reader takes it. Also whether the file says `root = true`.
let definesInText (text: string) : (string list * string list) option * bool =
    let mutable value = None
    let mutable isRoot = false
    let mutable inPreamble = true

    for raw in text.Split '\n' do
        let line = raw.Trim()

        if line.StartsWith "[" then
            inPreamble <- false
        elif line = "" || line.StartsWith "#" || line.StartsWith ";" then
            ()
        else
            match line.IndexOf '=' with
            | -1 -> ()
            | eq ->
                let key = line.Substring(0, eq).Trim().ToLowerInvariant()
                let v = line.Substring(eq + 1).Split('#').[0].Trim()

                if inPreamble && key = "root" then
                    isRoot <- String.Equals(v, "true", StringComparison.OrdinalIgnoreCase)
                elif key = DefinesKey then
                    value <- Some v

    let parsed =
        value
        |> Option.map (fun v ->
            let entries = RunDefines.pieces v |> List.distinct
            entries |> List.filter RunDefines.isSymbol, entries |> List.filter (RunDefines.isSymbol >> not))

    parsed, isRoot

/// The run's `csharp_refactor.defines`: from the `.editorconfig` nearest
/// `directory` that sets it, walking up to a `root = true` file — the file
/// it came from, its symbols, and its entries that are no symbol.
let definesFrom (directory: string) : (string * string list * string list) option =
    let rec walk (dir: string) =
        if String.IsNullOrEmpty dir then
            None
        else
            let path = Path.Combine(dir, ".editorconfig")

            let found, isRoot =
                try
                    if File.Exists path then
                        definesInText (File.ReadAllText path)
                    else
                        None, false
                with
                | :? IOException
                | :? UnauthorizedAccessException -> None, false

            match found with
            | Some(symbols, invalid) -> Some(path, symbols, invalid)
            | None when isRoot -> None
            | None -> walk (Path.GetDirectoryName dir)

    try
        walk (Path.GetFullPath directory)
    with
    | :? ArgumentException
    | :? PathTooLongException
    | :? NotSupportedException -> None

/// Write or append the block. Keys the existing file already sets are
/// left as they are and their lines dropped from the block.
let writeInto (directory: string) : Result<string, string> =
    let path = Path.Combine(directory, ".editorconfig")

    try
        let existing = if File.Exists path then File.ReadAllText path else ""

        if existing.Contains Marker then
            Error $"{path} already carries a csharp-refactor block — edit it, or delete the block to regenerate it."
        else
            let keyOf (l: string) =
                let m = Regex.Match(l, @"^\s*([A-Za-z0-9_.]+)\s*=")

                if m.Success then
                    Some(m.Groups.[1].Value.ToLowerInvariant())
                else
                    None

            let present = existing.Split('\n') |> Array.choose keyOf |> Set.ofArray

            let block =
                (defaultConfigText ()).Split('\n')
                |> Array.filter (fun l ->
                    match keyOf l with
                    | Some k -> not (present.Contains k)
                    | None -> true)
                |> String.concat "\n"

            let content =
                if existing = "" then "root = true\n\n" + block
                elif existing.EndsWith "\n" then existing + "\n" + block
                else existing + "\n\n" + block

            File.WriteAllText(path, content)
            Ok path
    with
    | :? IOException
    | :? UnauthorizedAccessException as e -> Error $"Could not write {path}: {e.Message}"
